### ISSUE TITLE
Vattenproblem

### ISSUE THREAD

**Issue by m-borjesson** [ETAChalmers/ETA_coffeedispenser#2]
Dispenserar inte vattnet ibland.

**Comment by sjaxel** [comment]
Fixat i 1079748d4d8b6d4a21c82ea5bc1249c32cdf3938

Felet uppstod i samband med att strömmen varit avstängd. Beklagar därmed alla kaffesugna som kommit dit på morgonen. Anledningen var att update-interrupt-flaggan inte var clearad ordentligt i init, vilket gjorde att den gick in interruptrutinen för att stänga av vattnet så fort man startat timern för att sätta igång det. Skall vara löst nu.
